version: "3"
services:
  bookstore:
    build: ./bookstore
    command: java -jar target/gs-rest-service-0.1.0.jar --server.port=80
    ports:
      - "80:80"
    networks:
      test:
  notes:
    build: ./notes
    command: python notes/app.py
    ports:
      - "5000:5000"
    container_name: notes
    volumes:
      - .:/code
    networks:
      test:

networks:
  test:
    driver: bridge
