bookstore:
  build: ./bookstore
  command: java -jar target/gs-rest-service-0.1.0.jar --server.port=80
  ports:
    - "80:80"
notes:
  build: ./notes
  command: python notes/app.py
  ports:
    - "5000:5000"
  container_name: notes
  volumes:
    - .:/code
